package org.example;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class EmailTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.gecko.driver", "geckodriver.exe");
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void email() {
        driver.get("https://www.booking.com/index.ru.html?label=gen173nr-1DCAEoggI46AdIM1gEaCWIAQGYASG4ARfIAQ_YAQPoAQGIAgGoAgO4AoiKqYkGwAIB0gIkMDhjOTZhZWEtMjYyNS00MjI4LWExMTUtZjZmNWI2OTUzNGUw2AIE4AIB;sid=3efb02db6af8ecdb0180e6640ca4842c;keep_landing=1&sb_price_type=total&");
        driver.manage().window().setSize(new Dimension(1920, 1080));
        js.executeScript("window.scrollTo(0,351.20001220703125)");
        driver.findElement(By.xpath("//div[@id=\'emk_banner_index\']/div[2]/div[2]/form/div/input")).click();
        driver.findElement(By.xpath("//div[@id=\'emk_banner_index\']/div[2]/div[2]/form/div/input")).sendKeys("sissergey@yandex.by");
        driver.findElement(By.xpath("//span[contains(.,\'Подписаться!\')]")).click();
    }
}
